services:
  - type: web
    name: somadecores-web
    runtime: python
    rootDir: SomadeCores
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_web:server
  - type: web
    name: estrelas-web
    runtime: static
    rootDir: ESTRELAS
    buildCommand: echo "Static site ready"
    staticPublishPath: ESTRELAS
